FROM ghcr.io/cross-rs/x86_64-unknown-linux-musl:latest

ARG DEBIAN_FRONTEND=noninteractive

COPY ./cec_build_prep.sh /
RUN /cec_build_prep.sh

COPY ./sccache.sh /
RUN /sccache.sh x86_64-unknown-linux-musl