# sha matching 2024-12-13
FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main@sha256:cf091033b6c4b0416a03d181080ad45c418248a262867a623306748a2c02a3c2

ARG DEBIAN_FRONTEND=noninteractive

COPY ./cec_build_prep.sh /
RUN /cec_build_prep.sh

COPY ./sccache.sh /
RUN /sccache.sh x86_64-unknown-linux-musl