FROM ghcr.io/cross-rs/x86_64-unknown-linux-gnu:latest

ARG DEBIAN_FRONTEND=noninteractive

COPY ./cec_build_prep.sh /
RUN /cec_build_prep.sh

COPY ./sccache.sh /
RUN /sccache.sh x86_64-unknown-linux-musl

ENV RUSTC_WRAPPER="/usr/bin/sccache"
ENV CMAKE_C_COMPILER_LAUNCHER="/usr/bin/sccache"
ENV CMAKE_CXX_COMPILER_LAUNCHER="/usr/bin/sccache"