#!/usr/bin/env bash
# Build the PoC against the real libCEC headers and assert the boundary matrix.
# Requires: a libCEC checkout (for include/cectypes.h + include/version.h.in).
#
#   ./run_poc.sh [path-to-libcec-checkout]
#
# Default checkout path is ../../vendor relative to this script (the libcec-sys
# submodule). Override by passing the path to any libCEC source tree.
set -u

here="$(cd "$(dirname "$0")" && pwd)"
libcec="${1:-$here/../../vendor}"
inc="$libcec/include"
work="$here/.build"
mkdir -p "$work"

if [ ! -f "$inc/cectypes.h" ]; then
  echo "error: $inc/cectypes.h not found; pass a libCEC checkout path" >&2
  exit 1
fi

# version.h is generated by CMake; synthesise a minimal one so cectypes.h
# compiles standalone.
if [ -f "$inc/version.h" ]; then
  cp "$inc/version.h" "$work/version.h"
else
  sed -e 's/@LIBCEC_VERSION_MAJOR@/6/g' \
      -e 's/@LIBCEC_VERSION_MINOR@/0/g' \
      -e 's/@LIBCEC_VERSION_PATCH@/0/g' \
      "$inc/version.h.in" > "$work/version.h"
fi

CXX="${CXX:-g++}"
"$CXX" -std=c++11 -g -O1 -fsanitize=address -fno-omit-frame-pointer \
  -I "$work" -I "$inc" \
  "$here/poc_adapter_overflow.cpp" -o "$work/poc" || { echo "build failed"; exit 1; }

export ASAN_OPTIONS="detect_leaks=0"

# adapter  safe_max  first_overflow
# Every case fills a 16-byte destination as [header][opcode][operands...], so
# the last safe operand count is 14 and operand 15 lands one byte past the end.
matrix="
exynos 14 15
aocec  14 15
tegra  14 15
linux  14 15
"

fail=0
printf '%-8s %-22s %-22s\n' "ADAPTER" "SAFE (expect clean)" "OVERFLOW (expect ASan)"
printf '%-8s %-22s %-22s\n' "-------" "-------------------" "----------------------"
while read -r name safe over; do
  [ -z "$name" ] && continue

  "$work/poc" "$name" "$safe" >/dev/null 2>&1
  safe_rc=$?
  "$work/poc" "$name" "$over" >/dev/null 2>&1
  over_rc=$?

  safe_ok="PASS"; [ "$safe_rc" -eq 0 ] || { safe_ok="FAIL"; fail=1; }
  over_ok="PASS"; [ "$over_rc" -ne 0 ] || { over_ok="FAIL"; fail=1; }

  printf '%-8s n=%-2d %-16s n=%-2d %-16s\n' \
    "$name" "$safe" "$safe_ok" "$over" "$over_ok"
done <<< "$matrix"

echo
if [ "$fail" -eq 0 ]; then
  echo "RESULT: all cases behaved as predicted (safe count clean, boundary count overflows)."
else
  echo "RESULT: some cases did not match expectations (see FAIL above)."
fi

echo
echo "Sample ASan report (exynos, 15 operands — 1-byte off-by-one):"
echo "-------------------------------------------------------------"
"$work/poc" exynos 15 2>&1 | grep -E "ERROR: AddressSanitizer|WRITE of size|#0 .*fill|overflows this variable" | head -5

echo
echo "Linux escalation (glibc _FORTIFY_SOURCE catches the whole-object overrun):"
echo "-------------------------------------------------------------------------"
"$work/poc" linux 64 2>&1 | grep -iE "buffer overflow detected|AddressSanitizer" | head -2

exit $fail
