/* automatically generated by rust-bindgen 0.71.1 */

pub type cec_abort_reason = ::std::os::raw::c_int;
pub type cec_analogue_broadcast_type = ::std::os::raw::c_int;
pub type cec_audio_rate = ::std::os::raw::c_int;
pub type cec_audio_status = ::std::os::raw::c_int;
pub type cec_boolean = ::std::os::raw::c_int;
pub type cec_version = ::std::os::raw::c_int;
pub type cec_channel_identifier = ::std::os::raw::c_int;
pub type cec_deck_control_mode = ::std::os::raw::c_int;
pub type cec_deck_info = ::std::os::raw::c_int;
pub type cec_device_type = ::std::os::raw::c_int;
pub type cec_display_control = ::std::os::raw::c_int;
pub type cec_external_source_specifier = ::std::os::raw::c_int;
pub type cec_menu_request_type = ::std::os::raw::c_int;
pub type cec_menu_state = ::std::os::raw::c_int;
pub type cec_play_mode = ::std::os::raw::c_int;
pub type cec_power_status = ::std::os::raw::c_int;
pub type cec_record_source_type = ::std::os::raw::c_int;
pub type cec_record_status_info = ::std::os::raw::c_int;
pub type cec_recording_sequence = ::std::os::raw::c_int;
pub type cec_status_request = ::std::os::raw::c_int;
pub type cec_system_audio_status = ::std::os::raw::c_int;
pub type cec_timer_cleared_status_data = ::std::os::raw::c_int;
pub type cec_timer_overlap_warning = ::std::os::raw::c_int;
pub type cec_media_info = ::std::os::raw::c_int;
pub type cec_programmed_indicator = ::std::os::raw::c_int;
pub type cec_programmed_info = ::std::os::raw::c_int;
pub type cec_not_programmed_error_info = ::std::os::raw::c_int;
pub type cec_recording_flag = ::std::os::raw::c_int;
pub type cec_tuner_display_info = ::std::os::raw::c_int;
pub type cec_broadcast_system = ::std::os::raw::c_int;
pub type cec_user_control_code = ::std::os::raw::c_int;
pub type cec_logical_address = ::std::os::raw::c_int;
pub type cec_opcode = ::std::os::raw::c_int;
pub type cec_log_level = ::std::os::raw::c_int;
pub type cec_bus_device_status = ::std::os::raw::c_int;
pub type cec_vendor_id = ::std::os::raw::c_int;
pub type cec_adapter_type = ::std::os::raw::c_int;
#[doc = " force exporting through swig"]
pub type libcec_version = ::std::os::raw::c_int;
pub type cec_menu_language = [::std::os::raw::c_char; 4usize];
pub type cec_osd_name = [::std::os::raw::c_char; 14usize];
pub type libcec_alert = ::std::os::raw::c_int;
pub type libcec_parameter_type = ::std::os::raw::c_int;
pub type libcec_connection_t = *mut ::std::os::raw::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_log_message {
    #[doc = "< the actual message, valid until returning from the log callback"]
    pub message: *const ::std::os::raw::c_char,
    #[doc = "< log level of the message"]
    pub level: cec_log_level,
    #[doc = "< the timestamp of this message"]
    pub time: i64,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_keypress {
    #[doc = "< the keycode"]
    pub keycode: cec_user_control_code,
    #[doc = "< the duration of the keypress"]
    pub duration: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_adapter {
    #[doc = "< the path to the com port"]
    pub path: [::std::os::raw::c_char; 1024usize],
    #[doc = "< the name of the com port"]
    pub comm: [::std::os::raw::c_char; 1024usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_adapter_descriptor {
    #[doc = "< the path to the com port"]
    pub strComPath: [::std::os::raw::c_char; 1024usize],
    #[doc = "< the name of the com port"]
    pub strComName: [::std::os::raw::c_char; 1024usize],
    pub iVendorId: u16,
    pub iProductId: u16,
    pub iFirmwareVersion: u16,
    pub iPhysicalAddress: u16,
    pub iFirmwareBuildDate: u32,
    pub adapterType: cec_adapter_type,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_datapacket {
    #[doc = "< the actual data"]
    pub data: [u8; 64usize],
    #[doc = "< the size of the data"]
    pub size: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_command {
    #[doc = "< the logical address of the initiator of this message"]
    pub initiator: cec_logical_address,
    #[doc = "< the logical address of the destination of this message"]
    pub destination: cec_logical_address,
    #[doc = "< 1 when the ACK bit is set, 0 otherwise"]
    pub ack: i8,
    #[doc = "< 1 when the EOM bit is set, 0 otherwise"]
    pub eom: i8,
    #[doc = "< the opcode of this message"]
    pub opcode: cec_opcode,
    #[doc = "< the parameters attached to this message"]
    pub parameters: cec_datapacket,
    #[doc = "< 1 when an opcode is set, 0 otherwise (POLL message)"]
    pub opcode_set: i8,
    #[doc = "< the timeout to use in ms"]
    pub transmit_timeout: i32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_device_type_list {
    #[doc = "< the list of device types"]
    pub types: [cec_device_type; 5usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cec_logical_addresses {
    #[doc = "< the primary logical address to use"]
    pub primary: cec_logical_address,
    #[doc = "< the list of addresses"]
    pub addresses: [::std::os::raw::c_int; 16usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libcec_parameter {
    #[doc = "< the type of this parameter"]
    pub paramType: libcec_parameter_type,
    #[doc = "< the value of this parameter"]
    pub paramData: *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct cec_adapter_stats {
    pub tx_ack: ::std::os::raw::c_uint,
    pub tx_nack: ::std::os::raw::c_uint,
    pub tx_error: ::std::os::raw::c_uint,
    pub rx_total: ::std::os::raw::c_uint,
    pub rx_error: ::std::os::raw::c_uint,
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct ICECCallbacks {
    #[doc = " @brief Transfer a log message from libCEC to the client.\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param message             The message to transfer."]
    pub logMessage: ::std::option::Option<
        unsafe extern "C" fn(cbparam: *mut ::std::os::raw::c_void, message: *const cec_log_message),
    >,
    #[doc = " @brief Transfer a keypress from libCEC to the client.\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param key                 The keypress to transfer."]
    pub keyPress: ::std::option::Option<
        unsafe extern "C" fn(cbparam: *mut ::std::os::raw::c_void, key: *const cec_keypress),
    >,
    #[doc = " @brief Transfer a CEC command from libCEC to the client.\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param command             The command to transfer."]
    pub commandReceived: ::std::option::Option<
        unsafe extern "C" fn(cbparam: *mut ::std::os::raw::c_void, command: *const cec_command),
    >,
    #[doc = " @brief Transfer a changed configuration from libCEC to the client\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param configuration       The configuration to transfer"]
    pub configurationChanged: ::std::option::Option<
        unsafe extern "C" fn(
            cbparam: *mut ::std::os::raw::c_void,
            configuration: *const libcec_configuration,
        ),
    >,
    #[doc = " @brief Transfer a libcec alert message from libCEC to the client\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param alert               The alert type transfer.\n @param data                Misc. additional information."]
    pub alert: ::std::option::Option<
        unsafe extern "C" fn(
            cbparam: *mut ::std::os::raw::c_void,
            alert: libcec_alert,
            param: libcec_parameter,
        ),
    >,
    #[doc = " @brief Transfer a menu state change to the client.\n Transfer a menu state change to the client. If the command returns 1, then the change will be processed by\n the busdevice. If 0, then the state of the busdevice won't be changed, and will always be kept 'activated',\n @warning CEC does not allow the player to suppress the menu state change on the TV, so the menu on the TV will always be displayed, whatever the return value of this method is.\n so keypresses are always routed.\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param state               The new value.\n\n @return 1 if libCEC should use this new value, 0 otherwise."]
    pub menuStateChanged: ::std::option::Option<
        unsafe extern "C" fn(
            cbparam: *mut ::std::os::raw::c_void,
            state: cec_menu_state,
        ) -> ::std::os::raw::c_int,
    >,
    #[doc = " @brief Called when a source that's handled by this client is activated.\n @param cbparam             Callback parameter provided when the callbacks were set up\n @param logicalAddress      The address that was just activated.\n @param bActivated          1 if activated, 0 when deactivated."]
    pub sourceActivated: ::std::option::Option<
        unsafe extern "C" fn(
            cbParam: *mut ::std::os::raw::c_void,
            logicalAddress: cec_logical_address,
            bActivated: u8,
        ),
    >,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct libcec_configuration {
    #[doc = "< the version of the client that is connecting"]
    pub clientVersion: u32,
    #[doc = "< the device name to use on the CEC bus, name + 0 terminator"]
    pub strDeviceName: [::std::os::raw::c_char; 15usize],
    #[doc = "< the device type(s) to use on the CEC bus for libCEC"]
    pub deviceTypes: cec_device_type_list,
    #[doc = "< (read only) set to 1 by libCEC when the physical address was autodetected"]
    pub bAutodetectAddress: u8,
    #[doc = "< the physical address of the CEC adapter"]
    pub iPhysicalAddress: u16,
    #[doc = "< the logical address of the device to which the adapter is connected. only used when iPhysicalAddress = 0 or when the adapter doesn't support autodetection"]
    pub baseDevice: cec_logical_address,
    #[doc = "< the HDMI port to which the adapter is connected. only used when iPhysicalAddress = 0 or when the adapter doesn't support autodetection"]
    pub iHDMIPort: u8,
    #[doc = "< override the vendor ID of the TV. leave this untouched to autodetect"]
    pub tvVendor: u32,
    #[doc = "< list of devices to wake when initialising libCEC or when calling PowerOnDevices() without any parameter."]
    pub wakeDevices: cec_logical_addresses,
    #[doc = "< list of devices to power off when calling StandbyDevices() without any parameter."]
    pub powerOffDevices: cec_logical_addresses,
    #[doc = "< the version number of the server. read-only"]
    pub serverVersion: u32,
    #[doc = "< true to get the settings from the ROM (if set, and a v2 ROM is present), false to use these settings."]
    pub bGetSettingsFromROM: u8,
    #[doc = "< make libCEC the active source on the bus when starting the player application"]
    pub bActivateSource: u8,
    #[doc = "< put this PC in standby mode when the TV is switched off. only used when bShutdownOnStandby = 0"]
    pub bPowerOffOnStandby: u8,
    #[doc = "< the object to pass along with a call of the callback methods. NULL to ignore"]
    pub callbackParam: *mut ::std::os::raw::c_void,
    #[doc = "< the callback methods to use. set this to NULL when not using callbacks"]
    pub callbacks: *mut ICECCallbacks,
    #[doc = "< (read-only) the current logical addresses. added in 1.5.3"]
    pub logicalAddresses: cec_logical_addresses,
    #[doc = "< (read-only) the firmware version of the adapter. added in 1.6.0"]
    pub iFirmwareVersion: u16,
    #[doc = "< the menu language used by the client. 3 character ISO 639-2 country code. see http://http://www.loc.gov/standards/iso639-2/ added in 1.6.2"]
    pub strDeviceLanguage: [::std::os::raw::c_char; 3usize],
    #[doc = "< (read-only) the build date of the firmware, in seconds since epoch. if not available, this value will be set to 0. added in 1.6.2"]
    pub iFirmwareBuildDate: u32,
    #[doc = "< won't allocate a CCECClient when starting the connection when set (same as monitor mode). added in 1.6.3"]
    pub bMonitorOnly: u8,
    #[doc = "< CEC spec version to use by libCEC. defaults to v1.4. added in 1.8.0"]
    pub cecVersion: cec_version,
    #[doc = "< type of the CEC adapter that we're connected to. added in 1.8.2"]
    pub adapterType: cec_adapter_type,
    #[doc = "< key code that initiates combo keys. defaults to CEC_USER_CONTROL_CODE_STOP. CEC_USER_CONTROL_CODE_UNKNOWN to disable. added in 2.0.5"]
    pub comboKey: cec_user_control_code,
    #[doc = "< timeout until the combo key is sent as normal keypress"]
    pub iComboKeyTimeoutMs: u32,
    #[doc = "< rate at which buttons autorepeat. 0 means rely on CEC device"]
    pub iButtonRepeatRateMs: u32,
    #[doc = "< duration after last update until a button is considered released"]
    pub iButtonReleaseDelayMs: u32,
    #[doc = "< prevent double taps within this timeout. defaults to 200ms. added in 4.0.0"]
    pub iDoubleTapTimeoutMs: u32,
    #[doc = "< set to 1 to automatically waking an AVR when the source is activated. added in 4.0.0"]
    pub bAutoWakeAVR: u8,
    #[doc = "< set to 1 and save eeprom config to wake the tv when usb is powered. added in 5.0.0 / fw v9"]
    pub bAutoPowerOn: u8,
}
pub const CEC_LIB_VERSION_MAJOR: u32 = 6;
pub const CEC_LIB_VERSION_MAJOR_STR: &[u8; 2] = b"6\0";
pub const CEC_LIB_VERSION_MINOR: u32 = 0;
pub const CEC_DEFAULT_PHYSICAL_ADDRESS: u32 = 4096;
pub const CEC_DEFAULT_HDMI_PORT: u32 = 1;
pub const CEC_DEFAULT_BASE_DEVICE: u32 = 0;
pub const CEC_BUTTON_TIMEOUT: u32 = 500;
pub const CEC_DOUBLE_TAP_TIMEOUT_MS: u32 = 200;
pub const CEC_POWER_STATE_REFRESH_TIME: u32 = 30000;
pub const CEC_FW_VERSION_UNKNOWN: u32 = 65535;
pub const CEC_FW_BUILD_UNKNOWN: u32 = 0;
pub const CEC_CONNECT_TRIES: u32 = 3;
pub const CEC_PHYSICAL_ADDRESS_TV: u32 = 0;
pub const CEC_MIN_PHYSICAL_ADDRESS: u32 = 4096;
pub const CEC_MAX_PHYSICAL_ADDRESS: u32 = 65534;
pub const CEC_INVALID_PHYSICAL_ADDRESS: u32 = 65535;
pub const CEC_MIN_VENDORID: u32 = 1;
pub const CEC_MAX_VENDORID: u32 = 16777214;
pub const CEC_INVALID_VENDORID: u32 = 16777215;
pub const CEC_MIN_HDMI_PORTNUMBER: u32 = 1;
pub const CEC_MAX_HDMI_PORTNUMBER: u32 = 15;
pub const CEC_HDMI_PORTNUMBER_NONE: u32 = 0;
pub const CEC_DEFAULT_SETTING_ACTIVATE_SOURCE: u32 = 1;
pub const CEC_DEFAULT_SETTING_POWER_OFF_SHUTDOWN: u32 = 1;
pub const CEC_DEFAULT_SETTING_POWER_OFF_ON_STANDBY: u32 = 1;
pub const CEC_DEFAULT_DEVICE_LANGUAGE: &[u8; 4] = b"eng\0";
pub const CEC_DEFAULT_SETTING_AUTODETECT_ADDRESS: u32 = 0;
pub const CEC_DEFAULT_SETTING_GET_SETTINGS_FROM_ROM: u32 = 0;
pub const CEC_DEFAULT_SETTING_CEC_VERSION: u32 = 5;
pub const CEC_DEFAULT_TRANSMIT_RETRY_WAIT: u32 = 500;
pub const CEC_DEFAULT_TRANSMIT_TIMEOUT: u32 = 1000;
pub const CEC_DEFAULT_TRANSMIT_WAIT: u32 = 1000;
pub const CEC_DEFAULT_TRANSMIT_RETRIES: u32 = 1;
pub const CEC_DEFAULT_CONNECT_TIMEOUT: u32 = 10000;
pub const CEC_DEFAULT_CONNECT_RETRY_WAIT: u32 = 1000;
pub const CEC_SERIAL_DEFAULT_BAUDRATE: u32 = 38400;
pub const CEC_CLEAR_INPUT_DEFAULT_WAIT: u32 = 1000;
pub const CEC_ACTIVE_SOURCE_SWITCH_RETRY_TIME_MS: u32 = 1000;
pub const CEC_FORWARD_STANDBY_MIN_INTERVAL: u32 = 10000;
pub const CEC_DEFAULT_COMBO_TIMEOUT_MS: u32 = 1000;
pub const CEC_RPI_VIRTUAL_PATH: &[u8; 13] = b"Raspberry Pi\0";
pub const CEC_RPI_VIRTUAL_COM: &[u8; 4] = b"RPI\0";
pub const CEC_TDA995x_PATH: &[u8; 13] = b"/dev/hdmicec\0";
pub const CEC_TDA995x_VIRTUAL_COM: &[u8; 6] = b"CuBox\0";
pub const CEC_EXYNOS_PATH: &[u8; 9] = b"/dev/CEC\0";
pub const CEC_EXYNOS_VIRTUAL_COM: &[u8; 7] = b"Exynos\0";
pub const CEC_MAX_DATA_PACKET_SIZE: u32 = 64;
pub const CEC_LINUX_PATH: &[u8; 10] = b"/dev/cec0\0";
pub const CEC_LINUX_VIRTUAL_COM: &[u8; 6] = b"Linux\0";
pub const CEC_AOCEC_PATH: &[u8; 11] = b"/dev/aocec\0";
pub const CEC_AOCEC_VIRTUAL_COM: &[u8; 6] = b"AOCEC\0";
pub const CEC_IMX_PATH: &[u8; 18] = b"/dev/mxc_hdmi_cec\0";
pub const CEC_IMX_VIRTUAL_COM: &[u8; 5] = b"i.MX\0";
pub const CEC_MIN_LIB_VERSION: u32 = 4;
pub const CEC_FEATURE_CONFIGURABLE_COMBO_KEY: u32 = 1;
pub const LIBCEC_OSD_NAME_SIZE: u32 = 15;
#[doc = "!< CEC_ABORT_REASON_UNRECOGNIZED_OPCODE"]
pub const cec_abort_reason_UNRECOGNIZED_OPCODE: cec_abort_reason = 0;
#[doc = "!< CEC_ABORT_REASON_NOT_IN_CORRECT_MODE_TO_RESPOND"]
pub const cec_abort_reason_NOT_IN_CORRECT_MODE_TO_RESPOND: cec_abort_reason = 1;
#[doc = "!< CEC_ABORT_REASON_CANNOT_PROVIDE_SOURCE"]
pub const cec_abort_reason_CANNOT_PROVIDE_SOURCE: cec_abort_reason = 2;
#[doc = "!< CEC_ABORT_REASON_INVALID_OPERAND"]
pub const cec_abort_reason_INVALID_OPERAND: cec_abort_reason = 3;
#[doc = "!< CEC_ABORT_REASON_REFUSED"]
pub const cec_abort_reason_REFUSED: cec_abort_reason = 4;
pub const cec_analogue_broadcast_type_CABLE: cec_analogue_broadcast_type = 0;
pub const cec_analogue_broadcast_type_SATELLITE: cec_analogue_broadcast_type = 1;
pub const cec_analogue_broadcast_type_TERRESTIAL: cec_analogue_broadcast_type = 2;
pub const cec_audio_rate_RATE_CONTROL_OFF: cec_audio_rate = 0;
pub const cec_audio_rate_STANDARD_RATE_100: cec_audio_rate = 1;
pub const cec_audio_rate_FAST_RATE_MAX_101: cec_audio_rate = 2;
pub const cec_audio_rate_SLOW_RATE_MIN_99: cec_audio_rate = 3;
pub const cec_audio_rate_STANDARD_RATE_100_0: cec_audio_rate = 4;
pub const cec_audio_rate_FAST_RATE_MAX_100_1: cec_audio_rate = 5;
pub const cec_audio_rate_SLOW_RATE_MIN_99_9: cec_audio_rate = 6;
pub const cec_audio_status_MUTE_STATUS_MASK: cec_audio_status = 128;
pub const cec_audio_status_VOLUME_STATUS_MASK: cec_audio_status = 127;
pub const cec_audio_status_VOLUME_MIN: cec_audio_status = 0;
pub const cec_audio_status_VOLUME_MAX: cec_audio_status = 100;
pub const cec_audio_status_VOLUME_STATUS_UNKNOWN: cec_audio_status = 127;
pub const cec_boolean_CEC_FALSE: cec_boolean = 0;
pub const cec_boolean_CEC_TRUE: cec_boolean = 1;
pub const cec_version_UNKNOWN: cec_version = 0;
pub const cec_version__1_2: cec_version = 1;
pub const cec_version__1_2A: cec_version = 2;
pub const cec_version__1_3: cec_version = 3;
pub const cec_version__1_3A: cec_version = 4;
pub const cec_version__1_4: cec_version = 5;
pub const cec_version__2_0: cec_version = 6;
pub const cec_channel_identifier_CEC_CHANNEL_NUMBER_FORMAT_MASK: cec_channel_identifier = -67108864;
pub const cec_channel_identifier_CEC_1_PART_CHANNEL_NUMBER: cec_channel_identifier = 67108864;
pub const cec_channel_identifier_CEC_2_PART_CHANNEL_NUMBER: cec_channel_identifier = 134217728;
pub const cec_channel_identifier_CEC_MAJOR_CHANNEL_NUMBER_MASK: cec_channel_identifier = 67043328;
pub const cec_channel_identifier_CEC_MINOR_CHANNEL_NUMBER_MASK: cec_channel_identifier = 65535;
pub const cec_deck_control_mode_SKIP_FORWARD_WIND: cec_deck_control_mode = 1;
pub const cec_deck_control_mode_SKIP_REVERSE_REWIND: cec_deck_control_mode = 2;
pub const cec_deck_control_mode_STOP: cec_deck_control_mode = 3;
pub const cec_deck_control_mode_EJECT: cec_deck_control_mode = 4;
pub const cec_deck_info_PLAY: cec_deck_info = 17;
pub const cec_deck_info_RECORD: cec_deck_info = 18;
pub const cec_deck_info_PLAY_REVERSE: cec_deck_info = 19;
pub const cec_deck_info_STILL: cec_deck_info = 20;
pub const cec_deck_info_SLOW: cec_deck_info = 21;
pub const cec_deck_info_SLOW_REVERSE: cec_deck_info = 22;
pub const cec_deck_info_FAST_FORWARD: cec_deck_info = 23;
pub const cec_deck_info_FAST_REVERSE: cec_deck_info = 24;
pub const cec_deck_info_NO_MEDIA: cec_deck_info = 25;
pub const cec_deck_info_STOP: cec_deck_info = 26;
pub const cec_deck_info_SKIP_FORWARD_WIND: cec_deck_info = 27;
pub const cec_deck_info_SKIP_REVERSE_REWIND: cec_deck_info = 28;
pub const cec_deck_info_INDEX_SEARCH_FORWARD: cec_deck_info = 29;
pub const cec_deck_info_INDEX_SEARCH_REVERSE: cec_deck_info = 30;
pub const cec_deck_info_OTHER_STATUS: cec_deck_info = 31;
pub const cec_deck_info_OTHER_STATUS_LG: cec_deck_info = 32;
pub const cec_device_type_TV: cec_device_type = 0;
pub const cec_device_type_RECORDING_DEVICE: cec_device_type = 1;
pub const cec_device_type_RESERVED: cec_device_type = 2;
pub const cec_device_type_TUNER: cec_device_type = 3;
pub const cec_device_type_PLAYBACK_DEVICE: cec_device_type = 4;
pub const cec_device_type_AUDIO_SYSTEM: cec_device_type = 5;
pub const cec_display_control_DISPLAY_FOR_DEFAULT_TIME: cec_display_control = 0;
pub const cec_display_control_DISPLAY_UNTIL_CLEARED: cec_display_control = 64;
pub const cec_display_control_CLEAR_PREVIOUS_MESSAGE: cec_display_control = 128;
pub const cec_display_control_RESERVED_FOR_FUTURE_USE: cec_display_control = 192;
pub const cec_external_source_specifier_EXTERNAL_PLUG: cec_external_source_specifier = 4;
pub const cec_external_source_specifier_EXTERNAL_PHYSICAL_ADDRESS: cec_external_source_specifier =
    5;
pub const cec_menu_request_type_ACTIVATE: cec_menu_request_type = 0;
pub const cec_menu_request_type_DEACTIVATE: cec_menu_request_type = 1;
pub const cec_menu_request_type_QUERY: cec_menu_request_type = 2;
pub const cec_menu_state_ACTIVATED: cec_menu_state = 0;
pub const cec_menu_state_DEACTIVATED: cec_menu_state = 1;
pub const cec_play_mode_PLAY_FORWARD: cec_play_mode = 36;
pub const cec_play_mode_PLAY_REVERSE: cec_play_mode = 32;
pub const cec_play_mode_PLAY_STILL: cec_play_mode = 37;
pub const cec_play_mode_FAST_FORWARD_MIN_SPEED: cec_play_mode = 5;
pub const cec_play_mode_FAST_FORWARD_MEDIUM_SPEED: cec_play_mode = 6;
pub const cec_play_mode_FAST_FORWARD_MAX_SPEED: cec_play_mode = 7;
pub const cec_play_mode_FAST_REVERSE_MIN_SPEED: cec_play_mode = 9;
pub const cec_play_mode_FAST_REVERSE_MEDIUM_SPEED: cec_play_mode = 10;
pub const cec_play_mode_FAST_REVERSE_MAX_SPEED: cec_play_mode = 11;
pub const cec_play_mode_SLOW_FORWARD_MIN_SPEED: cec_play_mode = 21;
pub const cec_play_mode_SLOW_FORWARD_MEDIUM_SPEED: cec_play_mode = 22;
pub const cec_play_mode_SLOW_FORWARD_MAX_SPEED: cec_play_mode = 23;
pub const cec_play_mode_SLOW_REVERSE_MIN_SPEED: cec_play_mode = 25;
pub const cec_play_mode_SLOW_REVERSE_MEDIUM_SPEED: cec_play_mode = 26;
pub const cec_play_mode_SLOW_REVERSE_MAX_SPEED: cec_play_mode = 27;
pub const cec_power_status_ON: cec_power_status = 0;
pub const cec_power_status_STANDBY: cec_power_status = 1;
pub const cec_power_status_IN_TRANSITION_STANDBY_TO_ON: cec_power_status = 2;
pub const cec_power_status_IN_TRANSITION_ON_TO_STANDBY: cec_power_status = 3;
pub const cec_power_status_UNKNOWN: cec_power_status = 153;
pub const cec_record_source_type_OWN_SOURCE: cec_record_source_type = 1;
pub const cec_record_source_type_DIGITAL_SERVICE: cec_record_source_type = 2;
pub const cec_record_source_type_ANALOGUE_SERVICE: cec_record_source_type = 3;
pub const cec_record_source_type_EXTERNAL_PLUS: cec_record_source_type = 4;
pub const cec_record_source_type_EXTERNAL_PHYSICAL_ADDRESS: cec_record_source_type = 5;
pub const cec_record_status_info_RECORDING_CURRENTLY_SELECTED_SOURCE: cec_record_status_info = 1;
pub const cec_record_status_info_RECORDING_DIGITAL_SERVICE: cec_record_status_info = 2;
pub const cec_record_status_info_RECORDING_ANALOGUE_SERVICE: cec_record_status_info = 3;
pub const cec_record_status_info_RECORDING_EXTERNAL_INPUT: cec_record_status_info = 4;
pub const cec_record_status_info_NO_RECORDING_UNABLE_TO_RECORD_DIGITAL_SERVICE:
    cec_record_status_info = 5;
pub const cec_record_status_info_NO_RECORDING_UNABLE_TO_RECORD_ANALOGUE_SERVICE:
    cec_record_status_info = 6;
pub const cec_record_status_info_NO_RECORDING_UNABLE_TO_SELECT_REQUIRED_SERVICE:
    cec_record_status_info = 7;
pub const cec_record_status_info_NO_RECORDING_INVALID_EXTERNAL_PLUG_NUMBER: cec_record_status_info =
    9;
pub const cec_record_status_info_NO_RECORDING_INVALID_EXTERNAL_ADDRESS: cec_record_status_info = 10;
pub const cec_record_status_info_NO_RECORDING_CA_SYSTEM_NOT_SUPPORTED: cec_record_status_info = 11;
pub const cec_record_status_info_NO_RECORDING_NO_OR_INSUFFICIENT_ENTITLEMENTS:
    cec_record_status_info = 12;
pub const cec_record_status_info_NO_RECORDING_NOT_ALLOWED_TO_COPY_SOURCE: cec_record_status_info =
    13;
pub const cec_record_status_info_NO_RECORDING_NO_FURTHER_COPIES_ALLOWED: cec_record_status_info =
    14;
pub const cec_record_status_info_NO_RECORDING_NO_MEDIA: cec_record_status_info = 16;
pub const cec_record_status_info_NO_RECORDING_PLAYING: cec_record_status_info = 17;
pub const cec_record_status_info_NO_RECORDING_ALREADY_RECORDING: cec_record_status_info = 18;
pub const cec_record_status_info_NO_RECORDING_MEDIA_PROTECTED: cec_record_status_info = 19;
pub const cec_record_status_info_NO_RECORDING_NO_SOURCE_SIGNAL: cec_record_status_info = 20;
pub const cec_record_status_info_NO_RECORDING_MEDIA_PROBLEM: cec_record_status_info = 21;
pub const cec_record_status_info_NO_RECORDING_NOT_ENOUGH_SPACE_AVAILABLE: cec_record_status_info =
    22;
pub const cec_record_status_info_NO_RECORDING_PARENTAL_LOCK_ON: cec_record_status_info = 23;
pub const cec_record_status_info_RECORDING_TERMINATED_NORMALLY: cec_record_status_info = 26;
pub const cec_record_status_info_RECORDING_HAS_ALREADY_TERMINATED: cec_record_status_info = 27;
pub const cec_record_status_info_NO_RECORDING_OTHER_REASON: cec_record_status_info = 31;
pub const cec_recording_sequence_SUNDAY: cec_recording_sequence = 1;
pub const cec_recording_sequence_MONDAY: cec_recording_sequence = 2;
pub const cec_recording_sequence_TUESDAY: cec_recording_sequence = 4;
pub const cec_recording_sequence_WEDNESDAY: cec_recording_sequence = 8;
pub const cec_recording_sequence_THURSDAY: cec_recording_sequence = 16;
pub const cec_recording_sequence_FRIDAY: cec_recording_sequence = 32;
pub const cec_recording_sequence_SATURDAY: cec_recording_sequence = 64;
pub const cec_recording_sequence_ONCE_ONLY: cec_recording_sequence = 0;
pub const cec_status_request_ON: cec_status_request = 1;
pub const cec_status_request_OFF: cec_status_request = 2;
pub const cec_status_request_ONCE: cec_status_request = 3;
pub const cec_system_audio_status_OFF: cec_system_audio_status = 0;
pub const cec_system_audio_status_ON: cec_system_audio_status = 1;
pub const cec_timer_cleared_status_data_TIMER_NOT_CLEARED_RECORDING: cec_timer_cleared_status_data =
    0;
pub const cec_timer_cleared_status_data_TIMER_NOT_CLEARED_NO_MATCHING:
    cec_timer_cleared_status_data = 1;
pub const cec_timer_cleared_status_data_TIMER_NOT_CLEARED_NO_INF0_AVAILABLE:
    cec_timer_cleared_status_data = 2;
pub const cec_timer_cleared_status_data_TIMER_CLEARED: cec_timer_cleared_status_data = 128;
pub const cec_timer_overlap_warning_NO_OVERLAP: cec_timer_overlap_warning = 0;
pub const cec_timer_overlap_warning_TIMER_BLOCKS_OVERLAP: cec_timer_overlap_warning = 1;
pub const cec_media_info_MEDIA_PRESENT_AND_NOT_PROTECTED: cec_media_info = 0;
pub const cec_media_info_MEDIA_PRESENT_BUT_PROTECTED: cec_media_info = 1;
pub const cec_media_info_MEDIA_NOT_PRESENT: cec_media_info = 2;
pub const cec_media_info_FUTURE_USE: cec_media_info = 3;
pub const cec_programmed_indicator_NOT_PROGRAMMED: cec_programmed_indicator = 0;
pub const cec_programmed_indicator_PROGRAMMED: cec_programmed_indicator = 1;
pub const cec_programmed_info_FUTURE_USE: cec_programmed_info = 0;
pub const cec_programmed_info_ENOUGH_SPACE_AVAILABLE_FOR_RECORDING: cec_programmed_info = 8;
pub const cec_programmed_info_NOT_ENOUGH_SPACE_AVAILABLE_FOR_RECORDING: cec_programmed_info = 9;
pub const cec_programmed_info_MAY_NOT_BE_ENOUGH_SPACE_AVAILABLE: cec_programmed_info = 11;
pub const cec_programmed_info_NO_MEDIA_INFO_AVAILABLE: cec_programmed_info = 10;
pub const cec_not_programmed_error_info_FUTURE_USE: cec_not_programmed_error_info = 0;
pub const cec_not_programmed_error_info_NO_FREE_TIMER_AVAILABLE: cec_not_programmed_error_info = 1;
pub const cec_not_programmed_error_info_DATE_OUT_OF_RANGE: cec_not_programmed_error_info = 2;
pub const cec_not_programmed_error_info_RECORDING_SEQUENCE_ERROR: cec_not_programmed_error_info = 3;
pub const cec_not_programmed_error_info_INVALID_EXTERNAL_PLUG_NUMBER:
    cec_not_programmed_error_info = 4;
pub const cec_not_programmed_error_info_INVALID_EXTERNAL_PHYSICAL_ADDRESS:
    cec_not_programmed_error_info = 5;
pub const cec_not_programmed_error_info_CA_SYSTEM_NOT_SUPPORTED: cec_not_programmed_error_info = 6;
pub const cec_not_programmed_error_info_NO_OR_INSUFFICIENT_CA_ENTITLEMENTS:
    cec_not_programmed_error_info = 7;
pub const cec_not_programmed_error_info_DOES_NOT_SUPPORT_RESOLUTION: cec_not_programmed_error_info =
    8;
pub const cec_not_programmed_error_info_PARENTAL_LOCK_ON: cec_not_programmed_error_info = 9;
pub const cec_not_programmed_error_info_CLOCK_FAILURE: cec_not_programmed_error_info = 10;
pub const cec_not_programmed_error_info_RESERVED_FOR_FUTURE_USE_START:
    cec_not_programmed_error_info = 11;
pub const cec_not_programmed_error_info_RESERVED_FOR_FUTURE_USE_END: cec_not_programmed_error_info =
    13;
pub const cec_not_programmed_error_info_DUPLICATE_ALREADY_PROGRAMMED:
    cec_not_programmed_error_info = 14;
pub const cec_recording_flag_NOT_BEING_USED_FOR_RECORDING: cec_recording_flag = 0;
pub const cec_recording_flag_BEING_USED_FOR_RECORDING: cec_recording_flag = 1;
pub const cec_tuner_display_info_DISPLAYING_DIGITAL_TUNER: cec_tuner_display_info = 0;
pub const cec_tuner_display_info_NOT_DISPLAYING_TUNER: cec_tuner_display_info = 1;
pub const cec_tuner_display_info_DISPLAYING_ANALOGUE_TUNER: cec_tuner_display_info = 2;
pub const cec_broadcast_system_PAL_B_G: cec_broadcast_system = 0;
pub const cec_broadcast_system_SECAM_L1: cec_broadcast_system = 1;
pub const cec_broadcast_system_PAL_M: cec_broadcast_system = 2;
pub const cec_broadcast_system_NTSC_M: cec_broadcast_system = 3;
pub const cec_broadcast_system_PAL_I: cec_broadcast_system = 4;
pub const cec_broadcast_system_SECAM_DK: cec_broadcast_system = 5;
pub const cec_broadcast_system_SECAM_B_G: cec_broadcast_system = 6;
pub const cec_broadcast_system_SECAM_L2: cec_broadcast_system = 7;
pub const cec_broadcast_system_PAL_DK: cec_broadcast_system = 8;
pub const cec_broadcast_system_OTHER_SYSTEM: cec_broadcast_system = 30;
pub const cec_user_control_code_SELECT: cec_user_control_code = 0;
pub const cec_user_control_code_UP: cec_user_control_code = 1;
pub const cec_user_control_code_DOWN: cec_user_control_code = 2;
pub const cec_user_control_code_LEFT: cec_user_control_code = 3;
pub const cec_user_control_code_RIGHT: cec_user_control_code = 4;
pub const cec_user_control_code_RIGHT_UP: cec_user_control_code = 5;
pub const cec_user_control_code_RIGHT_DOWN: cec_user_control_code = 6;
pub const cec_user_control_code_LEFT_UP: cec_user_control_code = 7;
pub const cec_user_control_code_LEFT_DOWN: cec_user_control_code = 8;
pub const cec_user_control_code_ROOT_MENU: cec_user_control_code = 9;
pub const cec_user_control_code_SETUP_MENU: cec_user_control_code = 10;
pub const cec_user_control_code_CONTENTS_MENU: cec_user_control_code = 11;
pub const cec_user_control_code_FAVORITE_MENU: cec_user_control_code = 12;
pub const cec_user_control_code_EXIT: cec_user_control_code = 13;
pub const cec_user_control_code_TOP_MENU: cec_user_control_code = 16;
pub const cec_user_control_code_DVD_MENU: cec_user_control_code = 17;
pub const cec_user_control_code_NUMBER_ENTRY_MODE: cec_user_control_code = 29;
pub const cec_user_control_code_NUMBER11: cec_user_control_code = 30;
pub const cec_user_control_code_NUMBER12: cec_user_control_code = 31;
pub const cec_user_control_code_NUMBER0: cec_user_control_code = 32;
pub const cec_user_control_code_NUMBER1: cec_user_control_code = 33;
pub const cec_user_control_code_NUMBER2: cec_user_control_code = 34;
pub const cec_user_control_code_NUMBER3: cec_user_control_code = 35;
pub const cec_user_control_code_NUMBER4: cec_user_control_code = 36;
pub const cec_user_control_code_NUMBER5: cec_user_control_code = 37;
pub const cec_user_control_code_NUMBER6: cec_user_control_code = 38;
pub const cec_user_control_code_NUMBER7: cec_user_control_code = 39;
pub const cec_user_control_code_NUMBER8: cec_user_control_code = 40;
pub const cec_user_control_code_NUMBER9: cec_user_control_code = 41;
pub const cec_user_control_code_DOT: cec_user_control_code = 42;
pub const cec_user_control_code_ENTER: cec_user_control_code = 43;
pub const cec_user_control_code_CLEAR: cec_user_control_code = 44;
pub const cec_user_control_code_NEXT_FAVORITE: cec_user_control_code = 47;
pub const cec_user_control_code_CHANNEL_UP: cec_user_control_code = 48;
pub const cec_user_control_code_CHANNEL_DOWN: cec_user_control_code = 49;
pub const cec_user_control_code_PREVIOUS_CHANNEL: cec_user_control_code = 50;
pub const cec_user_control_code_SOUND_SELECT: cec_user_control_code = 51;
pub const cec_user_control_code_INPUT_SELECT: cec_user_control_code = 52;
pub const cec_user_control_code_DISPLAY_INFORMATION: cec_user_control_code = 53;
pub const cec_user_control_code_HELP: cec_user_control_code = 54;
pub const cec_user_control_code_PAGE_UP: cec_user_control_code = 55;
pub const cec_user_control_code_PAGE_DOWN: cec_user_control_code = 56;
pub const cec_user_control_code_POWER: cec_user_control_code = 64;
pub const cec_user_control_code_VOLUME_UP: cec_user_control_code = 65;
pub const cec_user_control_code_VOLUME_DOWN: cec_user_control_code = 66;
pub const cec_user_control_code_MUTE: cec_user_control_code = 67;
pub const cec_user_control_code_PLAY: cec_user_control_code = 68;
pub const cec_user_control_code_STOP: cec_user_control_code = 69;
pub const cec_user_control_code_PAUSE: cec_user_control_code = 70;
pub const cec_user_control_code_RECORD: cec_user_control_code = 71;
pub const cec_user_control_code_REWIND: cec_user_control_code = 72;
pub const cec_user_control_code_FAST_FORWARD: cec_user_control_code = 73;
pub const cec_user_control_code_EJECT: cec_user_control_code = 74;
pub const cec_user_control_code_FORWARD: cec_user_control_code = 75;
pub const cec_user_control_code_BACKWARD: cec_user_control_code = 76;
pub const cec_user_control_code_STOP_RECORD: cec_user_control_code = 77;
pub const cec_user_control_code_PAUSE_RECORD: cec_user_control_code = 78;
pub const cec_user_control_code_ANGLE: cec_user_control_code = 80;
pub const cec_user_control_code_SUB_PICTURE: cec_user_control_code = 81;
pub const cec_user_control_code_VIDEO_ON_DEMAND: cec_user_control_code = 82;
pub const cec_user_control_code_ELECTRONIC_PROGRAM_GUIDE: cec_user_control_code = 83;
pub const cec_user_control_code_TIMER_PROGRAMMING: cec_user_control_code = 84;
pub const cec_user_control_code_INITIAL_CONFIGURATION: cec_user_control_code = 85;
pub const cec_user_control_code_SELECT_BROADCAST_TYPE: cec_user_control_code = 86;
pub const cec_user_control_code_SELECT_SOUND_PRESENTATION: cec_user_control_code = 87;
pub const cec_user_control_code_PLAY_FUNCTION: cec_user_control_code = 96;
pub const cec_user_control_code_PAUSE_PLAY_FUNCTION: cec_user_control_code = 97;
pub const cec_user_control_code_RECORD_FUNCTION: cec_user_control_code = 98;
pub const cec_user_control_code_PAUSE_RECORD_FUNCTION: cec_user_control_code = 99;
pub const cec_user_control_code_STOP_FUNCTION: cec_user_control_code = 100;
pub const cec_user_control_code_MUTE_FUNCTION: cec_user_control_code = 101;
pub const cec_user_control_code_RESTORE_VOLUME_FUNCTION: cec_user_control_code = 102;
pub const cec_user_control_code_TUNE_FUNCTION: cec_user_control_code = 103;
pub const cec_user_control_code_SELECT_MEDIA_FUNCTION: cec_user_control_code = 104;
pub const cec_user_control_code_SELECT_AV_INPUT_FUNCTION: cec_user_control_code = 105;
pub const cec_user_control_code_SELECT_AUDIO_INPUT_FUNCTION: cec_user_control_code = 106;
pub const cec_user_control_code_POWER_TOGGLE_FUNCTION: cec_user_control_code = 107;
pub const cec_user_control_code_POWER_OFF_FUNCTION: cec_user_control_code = 108;
pub const cec_user_control_code_POWER_ON_FUNCTION: cec_user_control_code = 109;
pub const cec_user_control_code_F1_BLUE: cec_user_control_code = 113;
pub const cec_user_control_code_F2_RED: cec_user_control_code = 114;
pub const cec_user_control_code_F3_GREEN: cec_user_control_code = 115;
pub const cec_user_control_code_F4_YELLOW: cec_user_control_code = 116;
pub const cec_user_control_code_F5: cec_user_control_code = 117;
pub const cec_user_control_code_DATA: cec_user_control_code = 118;
pub const cec_user_control_code_AN_RETURN: cec_user_control_code = 145;
pub const cec_user_control_code_AN_CHANNELS_LIST: cec_user_control_code = 150;
pub const cec_user_control_code_MAX: cec_user_control_code = 150;
pub const cec_user_control_code_UNKNOWN: cec_user_control_code = 255;
pub const cec_logical_address_UNKNOWN: cec_logical_address = -1;
pub const cec_logical_address_TV: cec_logical_address = 0;
pub const cec_logical_address_RECORDINGDEVICE1: cec_logical_address = 1;
pub const cec_logical_address_RECORDINGDEVICE2: cec_logical_address = 2;
pub const cec_logical_address_TUNER1: cec_logical_address = 3;
pub const cec_logical_address_PLAYBACKDEVICE1: cec_logical_address = 4;
pub const cec_logical_address_AUDIOSYSTEM: cec_logical_address = 5;
pub const cec_logical_address_TUNER2: cec_logical_address = 6;
pub const cec_logical_address_TUNER3: cec_logical_address = 7;
pub const cec_logical_address_PLAYBACKDEVICE2: cec_logical_address = 8;
pub const cec_logical_address_RECORDINGDEVICE3: cec_logical_address = 9;
pub const cec_logical_address_TUNER4: cec_logical_address = 10;
pub const cec_logical_address_PLAYBACKDEVICE3: cec_logical_address = 11;
pub const cec_logical_address_RESERVED1: cec_logical_address = 12;
pub const cec_logical_address_RESERVED2: cec_logical_address = 13;
pub const cec_logical_address_FREEUSE: cec_logical_address = 14;
pub const cec_logical_address_UNREGISTERED: cec_logical_address = 15;
pub const cec_logical_address_BROADCAST: cec_logical_address = 15;
pub const cec_opcode_ACTIVE_SOURCE: cec_opcode = 130;
pub const cec_opcode_IMAGE_VIEW_ON: cec_opcode = 4;
pub const cec_opcode_TEXT_VIEW_ON: cec_opcode = 13;
pub const cec_opcode_INACTIVE_SOURCE: cec_opcode = 157;
pub const cec_opcode_REQUEST_ACTIVE_SOURCE: cec_opcode = 133;
pub const cec_opcode_ROUTING_CHANGE: cec_opcode = 128;
pub const cec_opcode_ROUTING_INFORMATION: cec_opcode = 129;
pub const cec_opcode_SET_STREAM_PATH: cec_opcode = 134;
pub const cec_opcode_STANDBY: cec_opcode = 54;
pub const cec_opcode_RECORD_OFF: cec_opcode = 11;
pub const cec_opcode_RECORD_ON: cec_opcode = 9;
pub const cec_opcode_RECORD_STATUS: cec_opcode = 10;
pub const cec_opcode_RECORD_TV_SCREEN: cec_opcode = 15;
pub const cec_opcode_CLEAR_ANALOGUE_TIMER: cec_opcode = 51;
pub const cec_opcode_CLEAR_DIGITAL_TIMER: cec_opcode = 153;
pub const cec_opcode_CLEAR_EXTERNAL_TIMER: cec_opcode = 161;
pub const cec_opcode_SET_ANALOGUE_TIMER: cec_opcode = 52;
pub const cec_opcode_SET_DIGITAL_TIMER: cec_opcode = 151;
pub const cec_opcode_SET_EXTERNAL_TIMER: cec_opcode = 162;
pub const cec_opcode_SET_TIMER_PROGRAM_TITLE: cec_opcode = 103;
pub const cec_opcode_TIMER_CLEARED_STATUS: cec_opcode = 67;
pub const cec_opcode_TIMER_STATUS: cec_opcode = 53;
pub const cec_opcode_CEC_VERSION: cec_opcode = 158;
pub const cec_opcode_GET_CEC_VERSION: cec_opcode = 159;
pub const cec_opcode_GIVE_PHYSICAL_ADDRESS: cec_opcode = 131;
pub const cec_opcode_GET_MENU_LANGUAGE: cec_opcode = 145;
pub const cec_opcode_REPORT_PHYSICAL_ADDRESS: cec_opcode = 132;
pub const cec_opcode_SET_MENU_LANGUAGE: cec_opcode = 50;
pub const cec_opcode_DECK_CONTROL: cec_opcode = 66;
pub const cec_opcode_DECK_STATUS: cec_opcode = 27;
pub const cec_opcode_GIVE_DECK_STATUS: cec_opcode = 26;
pub const cec_opcode_PLAY: cec_opcode = 65;
pub const cec_opcode_GIVE_TUNER_DEVICE_STATUS: cec_opcode = 8;
pub const cec_opcode_SELECT_ANALOGUE_SERVICE: cec_opcode = 146;
pub const cec_opcode_SELECT_DIGITAL_SERVICE: cec_opcode = 147;
pub const cec_opcode_TUNER_DEVICE_STATUS: cec_opcode = 7;
pub const cec_opcode_TUNER_STEP_DECREMENT: cec_opcode = 6;
pub const cec_opcode_TUNER_STEP_INCREMENT: cec_opcode = 5;
pub const cec_opcode_DEVICE_VENDOR_ID: cec_opcode = 135;
pub const cec_opcode_GIVE_DEVICE_VENDOR_ID: cec_opcode = 140;
pub const cec_opcode_VENDOR_COMMAND: cec_opcode = 137;
pub const cec_opcode_VENDOR_COMMAND_WITH_ID: cec_opcode = 160;
pub const cec_opcode_VENDOR_REMOTE_BUTTON_DOWN: cec_opcode = 138;
pub const cec_opcode_VENDOR_REMOTE_BUTTON_UP: cec_opcode = 139;
pub const cec_opcode_SET_OSD_STRING: cec_opcode = 100;
pub const cec_opcode_GIVE_OSD_NAME: cec_opcode = 70;
pub const cec_opcode_SET_OSD_NAME: cec_opcode = 71;
pub const cec_opcode_MENU_REQUEST: cec_opcode = 141;
pub const cec_opcode_MENU_STATUS: cec_opcode = 142;
pub const cec_opcode_USER_CONTROL_PRESSED: cec_opcode = 68;
pub const cec_opcode_USER_CONTROL_RELEASE: cec_opcode = 69;
pub const cec_opcode_GIVE_DEVICE_POWER_STATUS: cec_opcode = 143;
pub const cec_opcode_REPORT_POWER_STATUS: cec_opcode = 144;
pub const cec_opcode_FEATURE_ABORT: cec_opcode = 0;
pub const cec_opcode_ABORT: cec_opcode = 255;
pub const cec_opcode_GIVE_AUDIO_STATUS: cec_opcode = 113;
pub const cec_opcode_GIVE_SYSTEM_AUDIO_MODE_STATUS: cec_opcode = 125;
pub const cec_opcode_REPORT_AUDIO_STATUS: cec_opcode = 122;
pub const cec_opcode_SET_SYSTEM_AUDIO_MODE: cec_opcode = 114;
pub const cec_opcode_SYSTEM_AUDIO_MODE_REQUEST: cec_opcode = 112;
pub const cec_opcode_SYSTEM_AUDIO_MODE_STATUS: cec_opcode = 126;
pub const cec_opcode_SET_AUDIO_RATE: cec_opcode = 154;
pub const cec_opcode_REPORT_SHORT_AUDIO_DESCRIPTORS: cec_opcode = 163;
pub const cec_opcode_REQUEST_SHORT_AUDIO_DESCRIPTORS: cec_opcode = 164;
pub const cec_opcode_START_ARC: cec_opcode = 192;
pub const cec_opcode_REPORT_ARC_STARTED: cec_opcode = 193;
pub const cec_opcode_REPORT_ARC_ENDED: cec_opcode = 194;
pub const cec_opcode_REQUEST_ARC_START: cec_opcode = 195;
pub const cec_opcode_REQUEST_ARC_END: cec_opcode = 196;
pub const cec_opcode_END_ARC: cec_opcode = 197;
pub const cec_opcode_CDC: cec_opcode = 248;
pub const cec_opcode_NONE: cec_opcode = 253;
pub const cec_log_level_CEC_LOG_ERROR: cec_log_level = 1;
pub const cec_log_level_CEC_LOG_WARNING: cec_log_level = 2;
pub const cec_log_level_CEC_LOG_NOTICE: cec_log_level = 4;
pub const cec_log_level_CEC_LOG_TRAFFIC: cec_log_level = 8;
pub const cec_log_level_CEC_LOG_DEBUG: cec_log_level = 16;
pub const cec_log_level_CEC_LOG_ALL: cec_log_level = 31;
pub const cec_bus_device_status_UNKNOWN: cec_bus_device_status = 0;
pub const cec_bus_device_status_PRESENT: cec_bus_device_status = 1;
pub const cec_bus_device_status_NOT_PRESENT: cec_bus_device_status = 2;
pub const cec_bus_device_status_HANDLED_BY_LIBCEC: cec_bus_device_status = 3;
pub const cec_vendor_id_TOSHIBA: cec_vendor_id = 57;
pub const cec_vendor_id_SAMSUNG: cec_vendor_id = 240;
pub const cec_vendor_id_DENON: cec_vendor_id = 1485;
pub const cec_vendor_id_MARANTZ: cec_vendor_id = 1656;
pub const cec_vendor_id_LOEWE: cec_vendor_id = 2434;
pub const cec_vendor_id_ONKYO: cec_vendor_id = 2480;
pub const cec_vendor_id_MEDION: cec_vendor_id = 3256;
pub const cec_vendor_id_TOSHIBA2: cec_vendor_id = 3303;
pub const cec_vendor_id_APPLE: cec_vendor_id = 4346;
pub const cec_vendor_id_PULSE_EIGHT: cec_vendor_id = 5506;
pub const cec_vendor_id_HARMAN_KARDON2: cec_vendor_id = 6480;
pub const cec_vendor_id_GOOGLE: cec_vendor_id = 6673;
pub const cec_vendor_id_AKAI: cec_vendor_id = 8391;
pub const cec_vendor_id_AOC: cec_vendor_id = 9319;
pub const cec_vendor_id_PANASONIC: cec_vendor_id = 32837;
pub const cec_vendor_id_PHILIPS: cec_vendor_id = 36926;
pub const cec_vendor_id_DAEWOO: cec_vendor_id = 36947;
pub const cec_vendor_id_YAMAHA: cec_vendor_id = 41182;
pub const cec_vendor_id_GRUNDIG: cec_vendor_id = 53461;
pub const cec_vendor_id_PIONEER: cec_vendor_id = 57398;
pub const cec_vendor_id_LG: cec_vendor_id = 57489;
pub const cec_vendor_id_SHARP: cec_vendor_id = 524319;
pub const cec_vendor_id_SONY: cec_vendor_id = 524358;
pub const cec_vendor_id_BROADCOM: cec_vendor_id = 1622150;
pub const cec_vendor_id_SHARP2: cec_vendor_id = 5458000;
pub const cec_vendor_id_VIZIO: cec_vendor_id = 7042157;
pub const cec_vendor_id_BENQ: cec_vendor_id = 8414697;
pub const cec_vendor_id_HARMAN_KARDON: cec_vendor_id = 10249310;
pub const cec_vendor_id_UNKNOWN: cec_vendor_id = 0;
pub const cec_adapter_type_UNKNOWN: cec_adapter_type = 0;
pub const cec_adapter_type_P8_EXTERNAL: cec_adapter_type = 1;
pub const cec_adapter_type_P8_DAUGHTERBOARD: cec_adapter_type = 2;
pub const cec_adapter_type_RPI: cec_adapter_type = 256;
pub const cec_adapter_type_TDA995x: cec_adapter_type = 512;
pub const cec_adapter_type_EXYNOS: cec_adapter_type = 768;
pub const cec_adapter_type_LINUX: cec_adapter_type = 1024;
pub const cec_adapter_type_AOCEC: cec_adapter_type = 1280;
pub const cec_adapter_type_IMX: cec_adapter_type = 1536;
pub const libcec_version_CURRENT: libcec_version = 393218;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_log_message"][::std::mem::size_of::<cec_log_message>() - 24usize];
    ["Alignment of cec_log_message"][::std::mem::align_of::<cec_log_message>() - 8usize];
    ["Offset of field: cec_log_message::message"]
        [::std::mem::offset_of!(cec_log_message, message) - 0usize];
    ["Offset of field: cec_log_message::level"]
        [::std::mem::offset_of!(cec_log_message, level) - 8usize];
    ["Offset of field: cec_log_message::time"]
        [::std::mem::offset_of!(cec_log_message, time) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_keypress"][::std::mem::size_of::<cec_keypress>() - 8usize];
    ["Alignment of cec_keypress"][::std::mem::align_of::<cec_keypress>() - 4usize];
    ["Offset of field: cec_keypress::keycode"]
        [::std::mem::offset_of!(cec_keypress, keycode) - 0usize];
    ["Offset of field: cec_keypress::duration"]
        [::std::mem::offset_of!(cec_keypress, duration) - 4usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_adapter"][::std::mem::size_of::<cec_adapter>() - 2048usize];
    ["Alignment of cec_adapter"][::std::mem::align_of::<cec_adapter>() - 1usize];
    ["Offset of field: cec_adapter::path"][::std::mem::offset_of!(cec_adapter, path) - 0usize];
    ["Offset of field: cec_adapter::comm"][::std::mem::offset_of!(cec_adapter, comm) - 1024usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_adapter_descriptor"][::std::mem::size_of::<cec_adapter_descriptor>() - 2064usize];
    ["Alignment of cec_adapter_descriptor"]
        [::std::mem::align_of::<cec_adapter_descriptor>() - 4usize];
    ["Offset of field: cec_adapter_descriptor::strComPath"]
        [::std::mem::offset_of!(cec_adapter_descriptor, strComPath) - 0usize];
    ["Offset of field: cec_adapter_descriptor::strComName"]
        [::std::mem::offset_of!(cec_adapter_descriptor, strComName) - 1024usize];
    ["Offset of field: cec_adapter_descriptor::iVendorId"]
        [::std::mem::offset_of!(cec_adapter_descriptor, iVendorId) - 2048usize];
    ["Offset of field: cec_adapter_descriptor::iProductId"]
        [::std::mem::offset_of!(cec_adapter_descriptor, iProductId) - 2050usize];
    ["Offset of field: cec_adapter_descriptor::iFirmwareVersion"]
        [::std::mem::offset_of!(cec_adapter_descriptor, iFirmwareVersion) - 2052usize];
    ["Offset of field: cec_adapter_descriptor::iPhysicalAddress"]
        [::std::mem::offset_of!(cec_adapter_descriptor, iPhysicalAddress) - 2054usize];
    ["Offset of field: cec_adapter_descriptor::iFirmwareBuildDate"]
        [::std::mem::offset_of!(cec_adapter_descriptor, iFirmwareBuildDate) - 2056usize];
    ["Offset of field: cec_adapter_descriptor::adapterType"]
        [::std::mem::offset_of!(cec_adapter_descriptor, adapterType) - 2060usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_datapacket"][::std::mem::size_of::<cec_datapacket>() - 65usize];
    ["Alignment of cec_datapacket"][::std::mem::align_of::<cec_datapacket>() - 1usize];
    ["Offset of field: cec_datapacket::data"]
        [::std::mem::offset_of!(cec_datapacket, data) - 0usize];
    ["Offset of field: cec_datapacket::size"]
        [::std::mem::offset_of!(cec_datapacket, size) - 64usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_command"][::std::mem::size_of::<cec_command>() - 88usize];
    ["Alignment of cec_command"][::std::mem::align_of::<cec_command>() - 4usize];
    ["Offset of field: cec_command::initiator"]
        [::std::mem::offset_of!(cec_command, initiator) - 0usize];
    ["Offset of field: cec_command::destination"]
        [::std::mem::offset_of!(cec_command, destination) - 4usize];
    ["Offset of field: cec_command::ack"][::std::mem::offset_of!(cec_command, ack) - 8usize];
    ["Offset of field: cec_command::eom"][::std::mem::offset_of!(cec_command, eom) - 9usize];
    ["Offset of field: cec_command::opcode"][::std::mem::offset_of!(cec_command, opcode) - 12usize];
    ["Offset of field: cec_command::parameters"]
        [::std::mem::offset_of!(cec_command, parameters) - 16usize];
    ["Offset of field: cec_command::opcode_set"]
        [::std::mem::offset_of!(cec_command, opcode_set) - 81usize];
    ["Offset of field: cec_command::transmit_timeout"]
        [::std::mem::offset_of!(cec_command, transmit_timeout) - 84usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_device_type_list"][::std::mem::size_of::<cec_device_type_list>() - 20usize];
    ["Alignment of cec_device_type_list"][::std::mem::align_of::<cec_device_type_list>() - 4usize];
    ["Offset of field: cec_device_type_list::types"]
        [::std::mem::offset_of!(cec_device_type_list, types) - 0usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_logical_addresses"][::std::mem::size_of::<cec_logical_addresses>() - 68usize];
    ["Alignment of cec_logical_addresses"]
        [::std::mem::align_of::<cec_logical_addresses>() - 4usize];
    ["Offset of field: cec_logical_addresses::primary"]
        [::std::mem::offset_of!(cec_logical_addresses, primary) - 0usize];
    ["Offset of field: cec_logical_addresses::addresses"]
        [::std::mem::offset_of!(cec_logical_addresses, addresses) - 4usize];
};
pub const libcec_alert_SERVICE_DEVICE: libcec_alert = 0;
pub const libcec_alert_CONNECTION_LOST: libcec_alert = 1;
pub const libcec_alert_PERMISSION_ERROR: libcec_alert = 2;
pub const libcec_alert_PORT_BUSY: libcec_alert = 3;
pub const libcec_alert_PHYSICAL_ADDRESS_ERROR: libcec_alert = 4;
pub const libcec_alert_TV_POLL_FAILED: libcec_alert = 5;
pub const libcec_parameter_type_STRING: libcec_parameter_type = 0;
pub const libcec_parameter_type_UNKOWN: libcec_parameter_type = 1;
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of libcec_parameter"][::std::mem::size_of::<libcec_parameter>() - 16usize];
    ["Alignment of libcec_parameter"][::std::mem::align_of::<libcec_parameter>() - 8usize];
    ["Offset of field: libcec_parameter::paramType"]
        [::std::mem::offset_of!(libcec_parameter, paramType) - 0usize];
    ["Offset of field: libcec_parameter::paramData"]
        [::std::mem::offset_of!(libcec_parameter, paramData) - 8usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cec_adapter_stats"][::std::mem::size_of::<cec_adapter_stats>() - 20usize];
    ["Alignment of cec_adapter_stats"][::std::mem::align_of::<cec_adapter_stats>() - 4usize];
    ["Offset of field: cec_adapter_stats::tx_ack"]
        [::std::mem::offset_of!(cec_adapter_stats, tx_ack) - 0usize];
    ["Offset of field: cec_adapter_stats::tx_nack"]
        [::std::mem::offset_of!(cec_adapter_stats, tx_nack) - 4usize];
    ["Offset of field: cec_adapter_stats::tx_error"]
        [::std::mem::offset_of!(cec_adapter_stats, tx_error) - 8usize];
    ["Offset of field: cec_adapter_stats::rx_total"]
        [::std::mem::offset_of!(cec_adapter_stats, rx_total) - 12usize];
    ["Offset of field: cec_adapter_stats::rx_error"]
        [::std::mem::offset_of!(cec_adapter_stats, rx_error) - 16usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ICECCallbacks"][::std::mem::size_of::<ICECCallbacks>() - 56usize];
    ["Alignment of ICECCallbacks"][::std::mem::align_of::<ICECCallbacks>() - 8usize];
    ["Offset of field: ICECCallbacks::logMessage"]
        [::std::mem::offset_of!(ICECCallbacks, logMessage) - 0usize];
    ["Offset of field: ICECCallbacks::keyPress"]
        [::std::mem::offset_of!(ICECCallbacks, keyPress) - 8usize];
    ["Offset of field: ICECCallbacks::commandReceived"]
        [::std::mem::offset_of!(ICECCallbacks, commandReceived) - 16usize];
    ["Offset of field: ICECCallbacks::configurationChanged"]
        [::std::mem::offset_of!(ICECCallbacks, configurationChanged) - 24usize];
    ["Offset of field: ICECCallbacks::alert"]
        [::std::mem::offset_of!(ICECCallbacks, alert) - 32usize];
    ["Offset of field: ICECCallbacks::menuStateChanged"]
        [::std::mem::offset_of!(ICECCallbacks, menuStateChanged) - 40usize];
    ["Offset of field: ICECCallbacks::sourceActivated"]
        [::std::mem::offset_of!(ICECCallbacks, sourceActivated) - 48usize];
};
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of libcec_configuration"][::std::mem::size_of::<libcec_configuration>() - 336usize];
    ["Alignment of libcec_configuration"][::std::mem::align_of::<libcec_configuration>() - 8usize];
    ["Offset of field: libcec_configuration::clientVersion"]
        [::std::mem::offset_of!(libcec_configuration, clientVersion) - 0usize];
    ["Offset of field: libcec_configuration::strDeviceName"]
        [::std::mem::offset_of!(libcec_configuration, strDeviceName) - 4usize];
    ["Offset of field: libcec_configuration::deviceTypes"]
        [::std::mem::offset_of!(libcec_configuration, deviceTypes) - 20usize];
    ["Offset of field: libcec_configuration::bAutodetectAddress"]
        [::std::mem::offset_of!(libcec_configuration, bAutodetectAddress) - 40usize];
    ["Offset of field: libcec_configuration::iPhysicalAddress"]
        [::std::mem::offset_of!(libcec_configuration, iPhysicalAddress) - 42usize];
    ["Offset of field: libcec_configuration::baseDevice"]
        [::std::mem::offset_of!(libcec_configuration, baseDevice) - 44usize];
    ["Offset of field: libcec_configuration::iHDMIPort"]
        [::std::mem::offset_of!(libcec_configuration, iHDMIPort) - 48usize];
    ["Offset of field: libcec_configuration::tvVendor"]
        [::std::mem::offset_of!(libcec_configuration, tvVendor) - 52usize];
    ["Offset of field: libcec_configuration::wakeDevices"]
        [::std::mem::offset_of!(libcec_configuration, wakeDevices) - 56usize];
    ["Offset of field: libcec_configuration::powerOffDevices"]
        [::std::mem::offset_of!(libcec_configuration, powerOffDevices) - 124usize];
    ["Offset of field: libcec_configuration::serverVersion"]
        [::std::mem::offset_of!(libcec_configuration, serverVersion) - 192usize];
    ["Offset of field: libcec_configuration::bGetSettingsFromROM"]
        [::std::mem::offset_of!(libcec_configuration, bGetSettingsFromROM) - 196usize];
    ["Offset of field: libcec_configuration::bActivateSource"]
        [::std::mem::offset_of!(libcec_configuration, bActivateSource) - 197usize];
    ["Offset of field: libcec_configuration::bPowerOffOnStandby"]
        [::std::mem::offset_of!(libcec_configuration, bPowerOffOnStandby) - 198usize];
    ["Offset of field: libcec_configuration::callbackParam"]
        [::std::mem::offset_of!(libcec_configuration, callbackParam) - 200usize];
    ["Offset of field: libcec_configuration::callbacks"]
        [::std::mem::offset_of!(libcec_configuration, callbacks) - 208usize];
    ["Offset of field: libcec_configuration::logicalAddresses"]
        [::std::mem::offset_of!(libcec_configuration, logicalAddresses) - 216usize];
    ["Offset of field: libcec_configuration::iFirmwareVersion"]
        [::std::mem::offset_of!(libcec_configuration, iFirmwareVersion) - 284usize];
    ["Offset of field: libcec_configuration::strDeviceLanguage"]
        [::std::mem::offset_of!(libcec_configuration, strDeviceLanguage) - 286usize];
    ["Offset of field: libcec_configuration::iFirmwareBuildDate"]
        [::std::mem::offset_of!(libcec_configuration, iFirmwareBuildDate) - 292usize];
    ["Offset of field: libcec_configuration::bMonitorOnly"]
        [::std::mem::offset_of!(libcec_configuration, bMonitorOnly) - 296usize];
    ["Offset of field: libcec_configuration::cecVersion"]
        [::std::mem::offset_of!(libcec_configuration, cecVersion) - 300usize];
    ["Offset of field: libcec_configuration::adapterType"]
        [::std::mem::offset_of!(libcec_configuration, adapterType) - 304usize];
    ["Offset of field: libcec_configuration::comboKey"]
        [::std::mem::offset_of!(libcec_configuration, comboKey) - 308usize];
    ["Offset of field: libcec_configuration::iComboKeyTimeoutMs"]
        [::std::mem::offset_of!(libcec_configuration, iComboKeyTimeoutMs) - 312usize];
    ["Offset of field: libcec_configuration::iButtonRepeatRateMs"]
        [::std::mem::offset_of!(libcec_configuration, iButtonRepeatRateMs) - 316usize];
    ["Offset of field: libcec_configuration::iButtonReleaseDelayMs"]
        [::std::mem::offset_of!(libcec_configuration, iButtonReleaseDelayMs) - 320usize];
    ["Offset of field: libcec_configuration::iDoubleTapTimeoutMs"]
        [::std::mem::offset_of!(libcec_configuration, iDoubleTapTimeoutMs) - 324usize];
    ["Offset of field: libcec_configuration::bAutoWakeAVR"]
        [::std::mem::offset_of!(libcec_configuration, bAutoWakeAVR) - 328usize];
    ["Offset of field: libcec_configuration::bAutoPowerOn"]
        [::std::mem::offset_of!(libcec_configuration, bAutoPowerOn) - 329usize];
};
impl Default for cec_log_message {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_keypress {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_adapter {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_adapter_descriptor {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_datapacket {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_command {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_device_type_list {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for cec_logical_addresses {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for libcec_parameter {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
impl Default for libcec_configuration {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn libcec_initialise(configuration: *mut libcec_configuration) -> libcec_connection_t;
    pub fn libcec_destroy(connection: libcec_connection_t);
    pub fn libcec_open(
        connection: libcec_connection_t,
        strPort: *const ::std::os::raw::c_char,
        iTimeout: u32,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_close(connection: libcec_connection_t);
    pub fn libcec_clear_configuration(configuration: *mut libcec_configuration);
    pub fn libcec_set_callbacks(
        connection: libcec_connection_t,
        callbacks: *mut ICECCallbacks,
        cbParam: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_disabled_callbacks(connection: libcec_connection_t) -> ::std::os::raw::c_int;
    pub fn libcec_find_adapters(
        connection: libcec_connection_t,
        deviceList: *mut cec_adapter,
        iBufSize: u8,
        strDevicePath: *const ::std::os::raw::c_char,
    ) -> i8;
    pub fn libcec_ping_adapters(connection: libcec_connection_t) -> ::std::os::raw::c_int;
    pub fn libcec_start_bootloader(connection: libcec_connection_t) -> ::std::os::raw::c_int;
    pub fn libcec_power_on_devices(
        connection: libcec_connection_t,
        address: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_standby_devices(
        connection: libcec_connection_t,
        address: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_active_source(
        connection: libcec_connection_t,
        type_: cec_device_type,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_deck_control_mode(
        connection: libcec_connection_t,
        mode: cec_deck_control_mode,
        bSendUpdate: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_deck_info(
        connection: libcec_connection_t,
        info: cec_deck_info,
        bSendUpdate: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_inactive_view(connection: libcec_connection_t) -> ::std::os::raw::c_int;
    pub fn libcec_set_menu_state(
        connection: libcec_connection_t,
        state: cec_menu_state,
        bSendUpdate: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_transmit(
        connection: libcec_connection_t,
        data: *const cec_command,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_logical_address(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_physical_address(
        connection: libcec_connection_t,
        iPhysicalAddress: u16,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_osd_string(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
        duration: cec_display_control,
        strMessage: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_switch_monitoring(
        connection: libcec_connection_t,
        bEnable: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_device_cec_version(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> cec_version;
    pub fn libcec_get_device_menu_language(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
        language: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_device_vendor_id(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> u32;
    pub fn libcec_get_device_physical_address(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> u16;
    pub fn libcec_get_active_source(connection: libcec_connection_t) -> cec_logical_address;
    pub fn libcec_is_active_source(
        connection: libcec_connection_t,
        iAddress: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_device_power_status(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> cec_power_status;
    pub fn libcec_poll_device(
        connection: libcec_connection_t,
        iLogicalAddress: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_active_devices(connection: libcec_connection_t) -> cec_logical_addresses;
    pub fn libcec_is_active_device(
        connection: libcec_connection_t,
        address: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_is_active_device_type(
        connection: libcec_connection_t,
        type_: cec_device_type,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_hdmi_port(
        connection: libcec_connection_t,
        baseDevice: cec_logical_address,
        iPort: u8,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_volume_up(
        connection: libcec_connection_t,
        bSendRelease: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_volume_down(
        connection: libcec_connection_t,
        bSendRelease: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_mute_audio(
        connection: libcec_connection_t,
        bSendRelease: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_send_keypress(
        connection: libcec_connection_t,
        iDestination: cec_logical_address,
        key: cec_user_control_code,
        bWait: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_send_key_release(
        connection: libcec_connection_t,
        iDestination: cec_logical_address,
        bWait: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_device_osd_name(
        connection: libcec_connection_t,
        iAddress: cec_logical_address,
        name: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_stream_path_logical(
        connection: libcec_connection_t,
        iAddress: cec_logical_address,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_set_stream_path_physical(
        connection: libcec_connection_t,
        iPhysicalAddress: u16,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_logical_addresses(connection: libcec_connection_t) -> cec_logical_addresses;
    pub fn libcec_get_current_configuration(
        connection: libcec_connection_t,
        configuration: *mut libcec_configuration,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_can_save_configuration(connection: libcec_connection_t) -> ::std::os::raw::c_int;
    pub fn libcec_set_configuration(
        connection: libcec_connection_t,
        configuration: *const libcec_configuration,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_rescan_devices(connection: libcec_connection_t);
    pub fn libcec_is_libcec_active_source(connection: libcec_connection_t)
        -> ::std::os::raw::c_int;
    pub fn libcec_get_device_information(
        connection: libcec_connection_t,
        strPort: *const ::std::os::raw::c_char,
        config: *mut libcec_configuration,
        iTimeoutMs: u32,
    ) -> ::std::os::raw::c_int;
    pub fn libcec_get_lib_info(connection: libcec_connection_t) -> *const ::std::os::raw::c_char;
    pub fn libcec_init_video_standalone(connection: libcec_connection_t);
    pub fn libcec_get_adapter_vendor_id(connection: libcec_connection_t) -> u16;
    pub fn libcec_get_adapter_product_id(connection: libcec_connection_t) -> u16;
    pub fn libcec_audio_toggle_mute(connection: libcec_connection_t) -> u8;
    pub fn libcec_audio_mute(connection: libcec_connection_t) -> u8;
    pub fn libcec_audio_unmute(connection: libcec_connection_t) -> u8;
    pub fn libcec_audio_get_status(connection: libcec_connection_t) -> u8;
    pub fn libcec_detect_adapters(
        connection: libcec_connection_t,
        deviceList: *mut cec_adapter_descriptor,
        iBufSize: u8,
        strDevicePath: *const ::std::os::raw::c_char,
        bQuickScan: ::std::os::raw::c_int,
    ) -> i8;
    pub fn libcec_menu_state_to_string(
        state: cec_menu_state,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_cec_version_to_string(
        version: cec_version,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_power_status_to_string(
        status: cec_power_status,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_logical_address_to_string(
        address: cec_logical_address,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_deck_control_mode_to_string(
        mode: cec_deck_control_mode,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_deck_status_to_string(
        status: cec_deck_info,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_opcode_to_string(
        opcode: cec_opcode,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_system_audio_status_to_string(
        mode: cec_system_audio_status,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_audio_status_to_string(
        status: cec_audio_status,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_vendor_id_to_string(
        vendor: cec_vendor_id,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_user_control_key_to_string(
        key: cec_user_control_code,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_adapter_type_to_string(
        type_: cec_adapter_type,
        buf: *mut ::std::os::raw::c_char,
        bufsize: usize,
    );
    pub fn libcec_version_to_string(version: u32, buf: *mut ::std::os::raw::c_char, bufsize: usize);
}
