name: Generate bindings

permissions:
  contents: write

on:
  push:
    branches: [main, win-improvements]

jobs:
  bindgen-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        libcec_major_version: ["4", "5", "6"]
    env:
      LIBCLANG_PATH: 'C:\Program Files\LLVM\lib'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bindgen windows
        uses: ./.github/actions/bindgen-windows
        with:
          target: x86_64-pc-windows-msvc
          major_version: ${{ matrix.libcec_major_version }}

#  bindgen-macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
#      - name: Bindgen macOS (Apple silicon)
#        uses: ./.github/actions/bindgen-unix
#        with:
#          target: aarch64-apple-darwin

  bindgen-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libcec_major_version: ["4", "5", "6"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bindgen unix
        uses: ./.github/actions/bindgen-unix
        with:
          target: x86_64-unknown-linux-gnu
          major_version: ${{ matrix.libcec_major_version }}
