name: Generate bindings

permissions:
  contents: write

on:
  push:
    branches: [main, win-improvements]

jobs:
  bindgen-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        libcec_major_version: ["4", "5", "6"]
    env:
      LIBCLANG_PATH: 'C:\Program Files\LLVM\lib'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.push.repository.full_name }}
          ref: ${{ github.event.push.ref }}

      - name: Bindgen windows
        uses: ./.github/actions/bindgen-windows
        with:
          target: x86_64-pc-windows-msvc
          libcec_major_version: ${{ matrix.libcec_major_version }}

      - name: Create pull request
        run: gh pr create -B master -H bindings_abi${{ matrix.libcec_major_version }}_x86_64-pc-windows-msvc --title 'Update libcec${{ matrix.libcec_major_version }} bindings x86_64-pc-windows-msvc' --body 'Created by Github action'
        shell: pwsh
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#  bindgen-macos:
#    runs-on: macos-latest
#    steps:
#      - name: Checkout repo
#        uses: actions/checkout@v4
#
#      - name: Bindgen macOS (Apple silicon)
#        uses: ./.github/actions/bindgen-unix
#        with:
#          target: aarch64-apple-darwin

  bindgen-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libcec_major_version: ["4", "5", "6"]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Bindgen unix
        uses: ./.github/actions/bindgen-unix
        with:
          target: x86_64-unknown-linux-gnu
          libcec_major_version: ${{ matrix.libcec_major_version }}

      - name: Create pull request
        run: gh pr create -B master -H bindings_abi${{ matrix.libcec_major_version }}_x86_64-unknown-linux-gnu --title 'Update libcec${{ matrix.libcec_major_version }} bindings x86_64-unknown-linux-gnu' --body 'Created by Github action'
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}