name: Continuous Deployment

on:
    push:
        tags:
            - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
    publish-cargo:
        name: Publishing to Cargo
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Apt-get update
              run: sudo apt-get update -yq
            - name: Install libudev for cargo publish. Needed by libcec build
              run: sudo apt-get install libudev-dev
            - name: Run sccache-cache
              uses: mozilla-actions/sccache-action@v0.0.3
            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  override: true
            - uses: actions-rs/cargo@v1
              with:
                  command: publish
                  args: --token ${{ secrets.CARGO_API_KEY }} --allow-dirty
              env:
                  SCCACHE_GHA_ENABLED: "true"
                  RUSTC_WRAPPER: "sccache"
                  LIBCEC_SYS_BUILD__CMAKE_C_COMPILER_LAUNCHER: "sccache"
                  LIBCEC_SYS_BUILD__CMAKE_CXX_COMPILER_LAUNCHER: "sccache"
